In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
!wget -O dataset.csv https://docs.google.com/spreadsheets/d/1lS9HEz8FreAkCpR_w_ykAHy3oWeQBqiuc_RJyr3dfbE/export?format=csv&gid=1322780754

--2024-08-24 06:14:55--  https://docs.google.com/spreadsheets/d/1lS9HEz8FreAkCpR_w_ykAHy3oWeQBqiuc_RJyr3dfbE/export?format=csv
Resolving docs.google.com (docs.google.com)... 172.217.204.113, 172.217.204.101, 172.217.204.139, ...
Connecting to docs.google.com (docs.google.com)|172.217.204.113|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://doc-08-1k-sheets.googleusercontent.com/export/54bogvaave6cua4cdnls17ksc4/hchr1es18fpjqapbkvhb6f8dso/1724480095000/100752720053680324863/*/1lS9HEz8FreAkCpR_w_ykAHy3oWeQBqiuc_RJyr3dfbE?format=csv [following]
Warning: wildcards not supported in HTTP.
--2024-08-24 06:14:55--  https://doc-08-1k-sheets.googleusercontent.com/export/54bogvaave6cua4cdnls17ksc4/hchr1es18fpjqapbkvhb6f8dso/1724480095000/100752720053680324863/*/1lS9HEz8FreAkCpR_w_ykAHy3oWeQBqiuc_RJyr3dfbE?format=csv
Resolving doc-08-1k-sheets.googleusercontent.com (doc-08-1k-sheets.googleusercontent.com)... 142.251.107.132, 2607:f8b0:400c:c32::84
Connecting to doc-08-1k-sheets.googleusercontent.com (doc-08-1k-sheets.googleusercontent.com)|142.251.107.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/csv]
Saving to: ‘dataset.csv’

dataset.csv             [   <=>              ]   6.53M  14.0MB/s    in 0.5s

2024-08-24 06:14:57 (14.0 MB/s) - ‘dataset.csv’ saved [6850374]

In [ ]:
file_path = '/content/dataset.csv'
df = pd.read_csv(file_path)

<ipython-input-23-9adb4d9a2db1>:2: DtypeWarning: Columns (9,14,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [ ]:
df

,Museum ID,Museum Name,Legal Name,Alternate Name,Museum Type,Institution Name,Street Address (Administrative Location),City (Administrative Location),State (Administrative Location),Zip Code (Administrative Location),...,Latitude,Longitude,Locale Code (NCES),County Code (FIPS),State Code (FIPS),Region Code (AAM),Employer ID Number,Tax Period,Income,Revenue
0,8400200098,ALASKA AVIATION HERITAGE MUSEUM,ALASKA AVIATION HERITAGE MUSEUM,NaN,HISTORY MUSEUM,NaN,4721 AIRCRAFT DR,ANCHORAGE,AK,99502,...,61.17925,-149.97254,1.0,20.0,2.0,6,920071852,201312.0,602912.0,550236.0
1,8400200117,ALASKA BOTANICAL GARDEN,ALASKA BOTANICAL GARDEN INC,NaN,"ARBORETUM, BOTANICAL GARDEN, OR NATURE CENTER",NaN,4601 CAMPBELL AIRSTRIP RD,ANCHORAGE,AK,99507,...,61.16890,-149.76708,4.0,20.0,2.0,6,920115504,201312.0,1379576.0,1323742.0
2,8400200153,ALASKA CHALLENGER CENTER FOR SPACE SCIENCE TEC...,ALASKA CHALLENGER CENTER FOR SPACE SCIENCE TEC...,NaN,SCIENCE & TECHNOLOGY MUSEUM OR PLANETARIUM,NaN,9711 KENAI SPUR HWY,KENAI,AK,99611,...,60.56149,-151.21598,3.0,122.0,2.0,6,921761906,201312.0,740030.0,729080.0
3,8400200143,ALASKA EDUCATORS HISTORICAL SOCIETY,ALASKA EDUCATORS HISTORICAL SOCIETY,NaN,HISTORIC PRESERVATION,NaN,214 BIRCH STREET,KENAI,AK,99611,...,60.56280,-151.26597,3.0,122.0,2.0,6,920165178,201412.0,0.0,0.0
4,8400200027,ALASKA HERITAGE MUSEUM,ALASKA AVIATION HERITAGE MUSEUM,NaN,HISTORY MUSEUM,NaN,301 W NORTHERN LIGHTS BLVD,ANCHORAGE,AK,99503,...,61.17925,-149.97254,1.0,20.0,2.0,6,920071852,201312.0,602912.0,550236.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33067,8405600184,WYOMING STATE HISTORICAL SOCIETY,WYOMING STATE HISTORICAL SOCIETY,NaN,HISTORIC PRESERVATION,NaN,PO BOX 73,SHERIDAN,WY,82801,...,44.82345,-106.87592,4.0,33.0,56.0,5,836007540.0,NaN,NaN,NaN
33068,8405600061,WYOMING STATE MUSEUM,WYOMING STATE MUSEUM VOLUNTEERS INC,NaN,GENERAL MUSEUM,NaN,2301 CENTRAL AVENUE,CHEYENNE,WY,82001,...,41.13941,-104.81813,1.0,21.0,56.0,5,237368629.0,201404.0,0.0,0.0
33069,8405600158,WYOMING TERRITORIAL PARK HISTORIC ASSOCIATION,WYOMING TERRITORIAL PARK HISTORIC ASSOCIATION INC,NaN,HISTORIC PRESERVATION,NaN,1273 N 15TH ST STE 121,LARAMIE,WY,82072,...,41.32276,-105.57686,3.0,1.0,56.0,5,830318392.0,201312.0,208508.0,83981.0
33070,8405600137,WYOMING TRANSPORTATION MUSEUM,WYOMING TRANSPORTATION MUSEUM CORP,NaN,HISTORY MUSEUM,NaN,PO BOX 704,CHEYENNE,WY,82003,...,41.13010,-104.81916,1.0,21.0,56.0,5,830295570.0,201309.0,0.0,0.0
33071,8405600199,YELLOWSTONE NATIONAL PARK,LITTLE PEOPLE LEARNING CENTER INC,NaN,HISTORIC PRESERVATION,NaN,NATIONAL PARK SERVICE,YELLOWSTONE NATIONAL PARK,WY,82190,...,44.91303,-110.41584,4.0,29.0,56.0,5,830249072.0,201312.0,127496.0,126762.0

# EDA

Code up the following concepts with regards to EDA.

*   Correlation
*   Mean, median, mode
In addition, write down inferences from the dataset.

In [ ]:
# Correlation

In [ ]:
# Mean, median and mode

### Inferences from the dataset

*   
*   
*   
*

# Preprocessing
Code up the following concepts with regards to Preprocessing. Justify the reason for using them for this specific dataset

*   Filling in missing values.
*   Encoding

Any other techniques that you might need, please justify their usage and code them up.

In [ ]:
# Filling in missing values

In [ ]:
# Encoding
# Hint: Figure out which columns need to be encoded. Would One-Hot Encoding be enough for handling this type of data? What are the alternatives?

In [ ]:
# Any other preprocessing...?

In [ ]:
# Final dataset

,Museum ID,Museum Name,Legal Name,Alternate Name,Museum Type,Institution Name,Street Address (Administrative Location),City (Administrative Location),State (Administrative Location),Zip Code (Administrative Location),...,Latitude,Longitude,Locale Code (NCES),County Code (FIPS),State Code (FIPS),Region Code (AAM),Employer ID Number,Tax Period,Income,Revenue
0,8400200098,ALASKA AVIATION HERITAGE MUSEUM,ALASKA AVIATION HERITAGE MUSEUM,NaN,HISTORY MUSEUM,NaN,4721 AIRCRAFT DR,153,0,99502,...,61.17925,-149.97254,1.0,20.0,2.0,6,920071852,201312.000000,6.029120e+05,5.502360e+05
1,8400200117,ALASKA BOTANICAL GARDEN,ALASKA BOTANICAL GARDEN INC,NaN,"ARBORETUM, BOTANICAL GARDEN, OR NATURE CENTER",NaN,4601 CAMPBELL AIRSTRIP RD,153,0,99507,...,61.16890,-149.76708,4.0,20.0,2.0,6,920115504,201312.000000,1.379576e+06,1.323742e+06
2,8400200153,ALASKA CHALLENGER CENTER FOR SPACE SCIENCE TEC...,ALASKA CHALLENGER CENTER FOR SPACE SCIENCE TEC...,NaN,SCIENCE & TECHNOLOGY MUSEUM OR PLANETARIUM,NaN,9711 KENAI SPUR HWY,3809,0,99611,...,60.56149,-151.21598,3.0,122.0,2.0,6,921761906,201312.000000,7.400300e+05,7.290800e+05
3,8400200143,ALASKA EDUCATORS HISTORICAL SOCIETY,ALASKA EDUCATORS HISTORICAL SOCIETY,NaN,HISTORIC PRESERVATION,NaN,214 BIRCH STREET,3809,0,99611,...,60.56280,-151.26597,3.0,122.0,2.0,6,920165178,201412.000000,0.000000e+00,0.000000e+00
4,8400200027,ALASKA HERITAGE MUSEUM,ALASKA AVIATION HERITAGE MUSEUM,NaN,HISTORY MUSEUM,NaN,301 W NORTHERN LIGHTS BLVD,153,0,99503,...,61.17925,-149.97254,1.0,20.0,2.0,6,920071852,201312.000000,6.029120e+05,5.502360e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33067,8405600184,WYOMING STATE HISTORICAL SOCIETY,WYOMING STATE HISTORICAL SOCIETY,NaN,HISTORIC PRESERVATION,NaN,PO BOX 73,7003,50,82801,...,44.82345,-106.87592,4.0,33.0,56.0,5,836007540.0,201347.458548,1.069682e+08,2.097605e+07
33068,8405600061,WYOMING STATE MUSEUM,WYOMING STATE MUSEUM VOLUNTEERS INC,NaN,GENERAL MUSEUM,NaN,2301 CENTRAL AVENUE,1323,50,82001,...,41.13941,-104.81813,1.0,21.0,56.0,5,237368629.0,201404.000000,0.000000e+00,0.000000e+00
33069,8405600158,WYOMING TERRITORIAL PARK HISTORIC ASSOCIATION,WYOMING TERRITORIAL PARK HISTORIC ASSOCIATION INC,NaN,HISTORIC PRESERVATION,NaN,1273 N 15TH ST STE 121,4101,50,82072,...,41.32276,-105.57686,3.0,1.0,56.0,5,830318392.0,201312.000000,2.085080e+05,8.398100e+04
33070,8405600137,WYOMING TRANSPORTATION MUSEUM,WYOMING TRANSPORTATION MUSEUM CORP,NaN,HISTORY MUSEUM,NaN,PO BOX 704,1323,50,82003,...,41.13010,-104.81916,1.0,21.0,56.0,5,830295570.0,201309.000000,0.000000e+00,0.000000e+00
33071,8405600199,YELLOWSTONE NATIONAL PARK,LITTLE PEOPLE LEARNING CENTER INC,NaN,HISTORIC PRESERVATION,NaN,NATIONAL PARK SERVICE,8575,50,82190,...,44.91303,-110.41584,4.0,29.0,56.0,5,830249072.0,201312.000000,1.274960e+05,1.267620e+05